language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
before_install:
- git config --global user.name "Travis CI"
- git config --global user.email "user@example.com"
env:
  global:
    secure: KG8W9hVvV2GpWP/I/GseiZ9bWHdd82MJYW2stN5RKzuVs0iZilt8mXFs0ozq1Y8v8ypkKobs9XBmMX+bSpgVlYqeRE7GvNaTafoESDvnxDwCisRJzSSrzIrfrMnW8u/fiw2HAcP9FkyE/pMvzTkqnQN3f8jcoWGKXN7MNArHN+XoTScMm3wJHIhchUPnI/F6KPpW0tj7vkIJCQ57lDskYZHdp6CEDY4vhkfmUdjhInRcYFT59sh/O6ERJ2VQVuHY202yj3GGVmvMz9FR3/l+tx3pJWYgjhW8ZBgGJlBUpT1OsKIn4/DSdBGKyyvBWs+VU+TEA9Q4Wg1A4pQQ2nbNlPNnKesXX/uxBoYT2Bn7TzuKwPTiiOq/pD3SRLiFSm2atA259tLWOSATtfAqmVe26zAyimyFfiJXA4L3Ck0S02wNWzs/hueIHZpINUGF9qMgKu38lvFlVlUM0/5E7RB3QH46/3RrV5h6eqs2Q3RmOZ1WUMk2ShSN3TDo44vf6D1smSwRe1rZvN9u494PGluEk05IqEav9/FFpwtZRj2qD2j7WGT6WF/6sBsAZ7SpXScmAYEQupV/EXqoSuChy2X6X54iYO9vzeqQs+0tGU2RG4dl+DjzHnoown1eISFrsionXvR6MR6/MA8eBTmUsWSXXYypexE52mVKwsWc5bbi12Y=
