title: Raincatcher documentation website
exclude:
  - LICENSE
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font

