title: Raincatcher documentation website
exclude:
  - LICENSE
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
asciidoc: 
  processor: asciidoctor
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  atrributes: 
    idseparator: _
    source-highlighter: coderay
    icons: font
    site-source: index.adoc

