[id='{context}-ref-ui-technology']
= The Technology and Structure of the User Interface in a {WFM-RC-NameShort} Project

The User Interface of {WFM-RC-NameShort} consists of a series of modules made available through the public NPM registry and built as modules the link:https://angularjs.org/[AngularJS Framework]. With extensive use of link:https://material.angularjs.org/latest/[Angular Material] as both a set of widgets and for general design.

The {WFM-RC-NameShort} modules are intended to be used as part of a regular AngularJS application and used by it as link:https://docs.angularjs.org/guide/module[AngularJS modules] they are kept in a separate, framework-specific repository on link:https://github.com/feedhenry-raincatcher/raincatcher-angularjs/[GitHub]

== Mobile app tooling

In addition to being a regular AngularJS application, the Mobile Starter App uses link:https://cordova.apache.org/[Apache Cordova] project to interface with the device's native resources. This setup allows for simple testability without requiring any actual mobile devices or emulators until the latest stages in the development cycle.
