[id='con-module-structures-and-relationships-{chapter}']
= Module Structures and Relationships

The Raincatcher Core modules act as the backend cloud server for the Raincathcer AngularJs applications.
The user space modules are used to interact between the client and portal on the Raincatcher AngularJS applications.

Raincatcher-AngularJS Application
|===
|raincatcher-demo-mobile | raincatcher-demo-portal

|Mobile application for WFM process users| Web application for WFM process administrators
|===

User Space Modules
|===
|vehicle-inspection-task

|===

Raincatcher Core Modules and Interfaces
|===
|raincatcher-wfm |raincatcher-security

|Workflow Management Framework, interface Task, interface Flow, interface Process|Security abstraction layer, class PassportAuth, Keycloak Middleware
|===

==  Module structure

RainCatcher core components are written in link:http://typescriptlang.org[TypeScript].

The main files are modules that by default export a class containing the main implementation for the module's intent,with a named export containing a public interface that should be depended upon, and reimplemented.

```typescript
import Implementation, { PublicInterface } from '@raincatcher/module';
```

== Default exports

Each module exports by default an implementation and set of interfaces by name.
Default implementation will usually implement most common use case for module.
Along with the default export, all modules include a public interface definition that are depended upon by other RainCatcher modules instead of depending on the implementation itself.

// Hard coded xref was required
For more information, see xref:ref-module-structures-and-relationships-raincatcher-reference-material[Module Structure and Relationship Reference Information].

