= WFM Common Steps

Common steps are the default steps that are available for usage for any Workflow. 
Common steps generally should do one thing well and should be generic enough to be added to any type of Workflow.
Developement of future common steps is in the Roadmap.

Roadmap:

* Plugable authentication
* Image capture
* Geolocation
* Internal Messaging and 3rd party Messaging
* Mobile Forms
* Real-time Data Access
* Integration of sensor data 

== Signature Common Step

{Feature} is shiped with the link:{WFM-RC-AngularJsURL}{WFM-RC-Branch}/steps/step-signature/[signature common step]. 
This is a generic step for implementing signatures in a Workflow.
This step is an extention of `fh-wfm-signature` FeedHenry WFM signature npm module for more information see the modules link:https://www.npmjs.com/package/fh-wfm-signature[documentation]. 
Like all steps Signature Common Step is made up of a `module` and a `definition` for more information on step makeup and usage see
xref:: {context}-con-workflow-step[Building your first Workflow Step].

=== Add Signature Common Step to mobile application
Add step to mobiles package.json as a package `/mobile/package.json`

[source,javascript]
---- 
    "@raincatcher/step-signature": "0.0.1",
----

Add step to mobiles `/mobile/src/app/app.js`
[source,javascript]
---- 
    // apply a variable name to the module
    var variableName = require('@raincatcher/step-signature');

    // add ngModule() for the module to angular.module array;
    variableName.ngModule();
----
Import the step scss for step-signature into `/mobile/src/sass/app.scss`
[source,javascript]
----    
    @import 'node_modules/@raincatcher/step-signaturebase/lib/signature.scss';
----
=== Add Signature Common Step to portal application

Add step package to `/portal/package.json`  
[source,javascript]
---- 
    "@raincatcher/step-signature": "0.0.1",                
----
Add step to portal in angular.modules in `/portal/src/app/main.js`
[source,javascript]
---- 
    // apply a variable name to the module
    var variableName = require(‘@raincatcher/step-signature);
----
Add step definition to angular.modules stepDefinitions array
[source,javascript]
---- 
    stepDefinitions: [
                        variableName.definition 
                     ]
----

Also add step ngModule() in angular.modules
[source,javascript]
---- 
    variableName.ngModule()
----

Import the step scss `/portal/src/sass/portal.scss`
[source,javascript]
---- 
    @import 'node_modules/@raincatcher/step-signature/lib/signature.scss';
----


