
[id='{context}-con-workflow-step']
= Adding a New Step to Your WFM Apps

Some knowledge of Angular.js is required to create a *Workflow Step* in {RainCatcher}.

== Introduction to Steps
Steps consists of:

* a module - one or more directives, See xref:wfm-step-module[]
* a definition - a json file, see xref:wfm-definition[]


[[wfm-step-module]]
=== WFM Step Module

{RainCatcher} steps use Angular.js directives to build a user interface. Modules contain one or more Angular.js directives to render steps in the Portal and Mobile applications.

Each step module consists of:

|===
|Directive |Description

|Edit Section directive (Form)
|a html template that allows users to edit information, typically, using a HTML form.

|Preview Section directive (View)
|a html template that displays a summary when the step is complete.

|===



[[wfm-definition]]
=== WFM Step Definition

A step definition outlines the properties of a step. For example, the name and the description of a step.
Each step requires a `definition.json` file and that file contains a definition of one or more steps. 
The following is an example of a `definition.json` file:

[source,json]
----
[
    {
        "code": "base-form",
        "name": "Base Form",
        "description": "base form used to for steps",
        "templates": {
            "form": "<base-form></base-form>",
            "view": "<base></base>"
        }
    }
]
----

[[developing-a-new-step]]
== Developing a New Step

To develop a new step:

. Create a directory for your step code.
. Populate the step directory using one of the following methods:
+
* Clone the link:https://github.com/feedhenry-raincatcher/step-template.git[step-template] repository.
+
* Follow the steps documented for the link:https://www.npmjs.com/package/generator-rcstep[generator-rcstep] npm package.
. Edit the _Edit Section_ directive, which is located in the `step-<step-name>/lib/angular/template/<step-name>-form.tpl.html` file.
+
For example to add a field for email, add the following to the `ng-form` div:
+
[source]
----
<md-input-container class="md-block" flex-gt-sm>
  <label>Email </label>
  <input type="text" id="title" name="title" ng-model="ctrl.model.email" required>
</md-input-container>
----


NOTE: The step module and step definition are exported from the `index.js` file, typically you do not edit this file.

[[adding-step-to-library]]
== Adding a Step to the Step Library

The step library is the set of steps that are available in the {Portal-App} to create workflows. For more information on workflows see <link>.

=== Adding Step Code to Mobile App

After developing a new step, as described in xref:developing-a-new-step[], add it to your Mobile  code as follows:

. Add a dependency entry for the step to your `package.json` file. For example:
+
----
"@raincatcher/step-<step-name>": "0.0.1",
----
. Add references to  your code. For example, to add references to the Starter Mobile App, you would edit `src/app/app.js` and add the following:
+
----
// apply a variable name to the module
var variableName = require(‘@raincatcher/step-<step-name>’);

// add ngModule() for the module to angular.module array;
variableName.ngModule();
----

=== Adding Step Code to {Portal-App}

After developing a new step, as described in xref:developing-a-new-step[], add it to your {Portal-App} code as follows:

. Add a dependency entry for the step to your `package.json` file. For example:
+
----
"@raincatcher/step-<step-name>": "0.0.1",
----
. Add references to  your code. For example, to add references to the Starter {Portal-App}:

.. Edit `src/app/main.js` and add the following:
+
----
// apply a variable name to the module
var variableName = require(‘@raincatcher/step-base’);
----
.. Add the step definition to the angular.modules stepDefinitions array
+
----
stepDefinitions: [
                    variableName.definition 
                 ]
----
.. Add the step ngModule() to the  `angular.modules` file:
+
----
variableName.ngModule()
----
.. Add reference to the step scss in the  `src/sass/portal.scss` file:
+
----
@import 'node_modules/@raincatcher/step-base/lib/step-base.scss';
----
