= WFM Common Steps

Common steps are the default steps that are available for usage for any Workflow. 
Common steps generally should do one thing well and should be generic enough to be added to any type of Workflow.
Developement of future common steps is in the Roadmap.

Roadmap:

* Plugable authentication
* Image capture
* Geolocation
* Internal Messaging and 3rd party Messaging
* Mobile Forms
* Real-time Data Access
* Integration of sensor data 

== Signature Common Step

{Feature} is shiped with the link:{WFM-RC-AngularJsURL}{WFM-RC-Branch}/steps/step-signature/[signature common step]. 
This is a generic step for implementing signatures for a Workflow. 
This step allow for the entry of a signature by a customer or employee.
Users can use a finger or stylus on a mobile device touch screen to enter a signature. 
Signatures are then stored as images to viewed as part of a completed workorder. 
Like all steps Signature Common Step is made up of a `module` and a `definition` for more information on step makeup and usage see
xref:: {context}-con-workflow-step[Building your first Workflow Step].
