== Getting Started

=== Requirements

- node/npm (tested on Node {WFM-NODE-VERSION})
- git
- mongodb 
- redis

=== Running 'demo' application

1. Clone git repository

        git clone git@github.com:feedhenry-raincatcher/raincatcher-angularjs.git
        cd raincatcher-angularjs
  
1. Install all dependencies for angular repository 

        npm install
        npm run bootstrap

> **Note**: Core repository will be automatically cloned using git command.
If you wish to work with different branch of the core repository please switch manually.

1. Install all dependencies for core repository

        cd ./core
        npm install
        npm run bootstrap

1. Start core node.js server

        npm run start

> **Note**: Core server requires mongodb and redis to be running on machine.

1. Start demo mobile and portal applications
Change directory to angular repository

        cd ..
        npm run start

Both demo mobile and demo portal should start automatically in your browser.

1. Use following credentials to login

**Portal User**

_Username_: `max`

_Password_: `123`

**Mobile User**

_Username_: `trever`

_Password_: `123`