
== About {WFM-RC-NameLong}

{WFM-RC-NameLong} is a Workforce Management platform with the main focus on delivering a set of modules and user interface for mobile user who want to integrate WFM features into their application.

{WFM-RC-NameLong} can be divided into the following areas:

- **Workforce Management framework** that provides set of the modules for building mobile and website
Workforce Management solutions
- **Set of modules** specific to Workforce management (signatures, scheduler etc.)
- **WFM specific integrations** to provide authentication, storage, offline capabilities and server side synchronization.
- **User interface** implemented in AngularJS and Angular

{WFM-RC-NameLong} includes:

- Hybrid mobile development using TypeScript(cordova/web/angular)
- Node.js based server
- Fully object oriented approach (classes and interfaces)
- Focus on reusability and developer flexibility
- All modules in single repository, multiple choice for user interfaces as separate repositories
- Comprehensive documentation
- Incorporates only open-source technologies

== Project repositories

The {WFM-RC-NameLong} is available as three github repositories:

- *Raincatcher-Core* (https://github.com/feedhenry-raincatcher/raincatcher-core)
Repository contains all of the supported modules and demo server.

- *Raincatcher-Angularjs*
Repository contains angularJS user interface for Raincatcher.

- *Raincatcher-Docs*
Repository contains RainCatcher documentation

=== Relation {WFM-RC-NameLong} Tech Preview

{WFM-RC-NameLong} *Tech Preview* information can be found at link:https://github.com/feedhenry-raincatcher/raincatcher-documentation[Beta Documentation].

Tech preview modules are available in github organization: https://github.com/orgs/raincatcher-beta

{WFM-RC-NameLong} {WFM-RC-VERSION} is the new version of the {WFM-RC-NameLong} *Tech Preview* framework.

The main changes compared to *Tech Preview* are as follows:

- Removed mediator pattern used in *Tech Preview*
- Introducted fully object oriented approach (Classes and Interfaces)
- Lightweight in code, with a focus on giving developers multiple choices
- TypeScript native (for better documentation and developer experience)
- All modules in single repository (core), multiple choice for user interfaces.