[id='pro-running-the-published-repositories-{chapter}']
= Introduction

The {WFM-RC-NameShort} demo applications are also available in separate repositories in GitHub, that require their dependencies from the public NPM Registry instead of requiring compilation via the TypeScript compiler and linking via Lerna.js.

This allows for a simpler setup for users that only require running the applications in a quick fashion, and will not engage in development for contribution to the project.

= Prerequisites

* Node and npm installed (tested on Node {WFM-RC-NodeVersion})
* git
* access to `git@github.com:feedhenry-raincatcher/raincatcher-server.git`
* access to `git@github.com:feedhenry-raincatcher/raincatcher-mobile.git`
* access to `git@github.com:feedhenry-raincatcher/raincatcher-portal.git`
* MongoDB (tested with version: {WFM-RC-MongoDBVersion})
* Redis (tested with version: {WFM-RC-RedisVersion})

= Running the Demo App from the Published Repositories

This procedure will install the latest published version of {WFM-RC-NameShort} from the separate, per-demo-app GitHub repositories.

ifdef::upstream[]
[discrete]
endif::upstream[]
== Cloning the Git Repositories

[source,bash]
----
git clone git@github.com:feedhenry-raincatcher/raincatcher-server.git
git clone git@github.com:feedhenry-raincatcher/raincatcher-mobile.git
git clone git@github.com:feedhenry-raincatcher/raincatcher-portal.git
----

ifdef::upstream[]
[discrete]
endif::upstream[]
== Installing Dependencies on the Repositories

For each repository cloned previously, run `npm install` so regular NPM dependencies are downloaded.

ifdef::upstream[]
[discrete]
endif::upstream[]
== Starting MongoDB and Redis

. Start MongoDB. For more information, see link:https://docs.mongodb.com/manual/tutorial/manage-mongodb-processes/#start-mongod-processes[Start MongoDB Processes].

. Start Redis. For more information, see link:https://redis.io/topics/quickstart#starting-redis[Starting Redis].

ifdef::upstream[]
[discrete]
endif::upstream[]
== Starting the Core Server

[source,bash]
----
cd raincatcher-server/
npm run start
----

ifdef::upstream[]
[discrete]
endif::upstream[]
== Running the Mobile and Portal Demo Applications

In new terminal windows, run the following commands on the `raincatcher-portal/` and `raincatcher-mobile/` folders.

[source,bash]
----
npm run start
----

Each of these commands will open the Mobile and Portal Demo the default web browser.

For login details, refer to xref:credentials-for-the-demo-application-{chapter}[Credentials for the Demo Application] section of xref:ref-demo-app-{chapter}[{WFM-RC-NameShort} Demo Application Reference Material].
