[id='{chapter}-pro-keycloak-implementation']
= Implementing {WFM-RC-KeycloakName}

This section includes:

. xref:{chapter}-initializing-keycloak[Initializing {WFM-RC-KeycloakName}]
. xref:{chapter}-importing-the-endpointsecurity-interface[Importing the EndpointSecurity Interface]
. xref:{chapter}-importing-keycloak-init[Importing {WFM-RC-KeycloakName} _init_]
. xref:{chapter}-applying-keycloak-init[Applying {WFM-RC-KeycloakName} _init_ ]
. xref:{chapter}-enabling-keycloak-route-protection[Enabling {WFM-RC-KeycloakName} Route Protection]

== Prerequisites

. Ensure you have completed xref:getting-started[Getting Started]
. Docker (tested with version: {WFM-RC-DockerVersion})

== Using {WFM-RC-KeycloakName} to secure endpoints

[id='{chapter}-initializing-keycloak']
[discrete]
=== Initializing {WFM-RC-KeycloakName}

See the link:{WFM-RC-CoreURL}{WFM-RC-Branch}/demo/server/src/modules/keycloak/index.ts[Keycloak code] for reference.

[id='{chapter}-importing-the-endpointsecurity-interface']
[discrete]
=== Importing The EndpointSecurity Interface

Import the link:{WFM-RC-CoreURL}{WFM-RC-Branch}/cloud/auth/src/EndpointSecurity.ts[EndpointSecurity Interface] and implement it.

[id='{chapter}-importing-keycloak-init']
[discrete]
=== Importing {WFM-RC-KeycloakName} _init_

Import *{WFM-RC-KeycloakName}* _init_ from link:{WFM-RC-CoreURL}{WFM-RC-Branch}/demo/server/src/modules/keycloak/index.ts[Keycloak]. For example:

[source,typescript]
----
import { init as initKeycloak } from './keycloak';
----

[id='{chapter}-applying-keycloak-init']
[discrete]
=== Applying {WFM-RC-KeycloakName} _init_

Apply *{WFM-RC-KeycloakName}* _init_ to the security Middleware to enable *{WFM-RC-KeycloakName}* for route protection.
See the link:{WFM-RC-CoreURL}{WFM-RC-Branch}/demo/server/src/modules/index.ts[securitySetup] code for more information.

[id='{chapter}-enabling-keycloak-route-protection']
[discrete]
=== Enabling {WFM-RC-KeycloakName} Route Protection

The following code is an example of how to protect routes:

[source,typescript]
----
// This implementation supports role based authentication
app.use('/test', securityMiddleware.protect(role));
----
