== Introduction

{WFM-RC-NameLong}  consist of set of npm modules written in TypeScript language that are packaged and distributed as
{WFM-RC-NameLong} provides a set of reusable components that can simplify mobile, web and cloud application development.
Solution allows developers to write secure, offline ready websites and mobile applications.
{WFM-RC-NameLong} provides Workforce Management oriented framework for Workforce Management applications.

Solution consist of two fully independent Frameworks:

 * Workforce Management
 * Security

===  Workforce Management Framework

{WFM-RC-NameLong} Workforce Management Framework builds a clear definition of the work required through engineered
standards and optimal methods for performing each task as efficiently and safely as possible.
WFM framework allows to build advanced Workforce Management solutions.
Framework helps to write solutions that connects a business back-office with its fleet of mobilized employees.

 * Task: defines single unit of work for business process
 * Flow: contain ordered set of tasks and handlers for executing tasks in proper order
 * Process: instance of flow containing current progress and business objects.

Users can write custom Tasks (Workflow Steps) that will implement any business logic and link implementation with any
UI solution.

{WFM-RC-NameLong} allows you to build production-grade Node.js and Cordova based applications from the
following technology stack.

|===
|TypeScript
|Cordova
|Node.js
|===

Main targets for framework:

* Rapid, production ready application development framework.
* Covers Mobile, web and server side application development
* Written in TypeScript (with support JavaScript development)
* Secure out of the box thanks to multiple security providers (Keycloak, Passport.js)
* Full support for offline enabled applications thanks to FeedHenry Sync
* Extensibility provided by set of TypeScript based interfaces
* Provide A sleek, modern, mobile enabled front-end reference applications
* Provides abstraction layer for common application elements:
    ** Data access
    ** Security
    ** Logging
    ** Restful API creation
    ** Unit testing

The Modules abstract from any application logic and technologies allowing developers to extend it for their needs.
